name: transport_sterlitamaka
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.1
  mapbox_gl: ^0.16.0
  mapbox_gl_platform_interface: ^0.16.0
  turf: ^0.0.7
  geolocator: ^9.0.2
  sqflite: ^2.2.4+1
  path: ^1.8.2
  dio: ^4.0.6
  web_socket_channel: ^2.3.0
  equatable: ^2.0.5
  provider: ^6.0.5
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/db.db
    - assets/schemes/
